version: '2.0'
services:
    node-red:
        # image: sax1johno/node-red-base
        build: .
        # container_name: "node-red"
        ports:
            - '80'
        restart: unless-stopped
        environment:
            - STORAGE=couch
        links:
            - couchdb
        depends_on:
            - couchdb
    couchdb:
        image: couchdb
        ports:
            - '5984'
        external_links:
            - upstream:upstream